/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 * Player panel for Record Match
 *
 * @author Nathan Ott and Fatih Ridha
 */
public class Player extends javax.swing.JPanel {

    /**
     * Creates new form Player.
     */
    public Player() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playerNameLabel = new javax.swing.JLabel();
        hitsSpinner = new javax.swing.JSpinner();
        catchesSpinner = new javax.swing.JSpinner();
        caughtOutSpinner = new javax.swing.JSpinner();
        hitOutSpinner = new javax.swing.JSpinner();
        throwsSpinner = new javax.swing.JSpinner();
        survivorCheck = new javax.swing.JCheckBox();

        playerNameLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        playerNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        playerNameLabel.setText("Name");

        hitsSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        hitsSpinner.setEnabled(false);

        catchesSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        catchesSpinner.setEnabled(false);

        caughtOutSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        caughtOutSpinner.setEnabled(false);

        hitOutSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        hitOutSpinner.setEnabled(false);

        throwsSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        throwsSpinner.setEnabled(false);

        survivorCheck.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(playerNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(throwsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(hitsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(catchesSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(caughtOutSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(hitOutSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(survivorCheck)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(hitsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(catchesSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(caughtOutSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(hitOutSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(throwsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(survivorCheck))
                    .addComponent(playerNameLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Sets label to player's name.
     *
     * @param name player name
     */
    public void setPlayerName(String name) {
        playerNameLabel.setText(name);
    }

    /**
     * Sets match enabled state of the player.
     *
     * @param enabled
     */
    public void setMatchEnabled(boolean enabled) {
        throwsSpinner.setEnabled(enabled);
        hitsSpinner.setEnabled(enabled);
        catchesSpinner.setEnabled(enabled);
        hitOutSpinner.setEnabled(enabled);
        caughtOutSpinner.setEnabled(enabled);
        survivorCheck.setEnabled(enabled);
    }

    /**
     * Returns players' name, throws, hits, catches, hit-outs, caught-outs, and
     * survival-bonus.
     *
     * @return HashMap of player's stats
     */
    public java.util.HashMap<String, Object> getStats() {
        java.util.HashMap<String, Object> stats = new java.util.LinkedHashMap();
        stats.put("match", 1);
        stats.put("player", playerNameLabel.getText());
        stats.put("team", "team");
        stats.put("throws", (int) (throwsSpinner.getValue()));
        stats.put("hits", (int) (hitsSpinner.getValue()));
        stats.put("catches", (int) (catchesSpinner.getValue()));
        stats.put("hout", (int) (hitOutSpinner.getValue()));
        stats.put("cout", (int) (caughtOutSpinner.getValue()));
        stats.put("sbonus", survivorCheck.isSelected() ? 1 : 0);
        return stats;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner catchesSpinner;
    private javax.swing.JSpinner caughtOutSpinner;
    private javax.swing.JSpinner hitOutSpinner;
    private javax.swing.JSpinner hitsSpinner;
    private javax.swing.JLabel playerNameLabel;
    private javax.swing.JCheckBox survivorCheck;
    private javax.swing.JSpinner throwsSpinner;
    // End of variables declaration//GEN-END:variables
}
