/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.DefaultListModel;
import model.DodgeballTableModel;
import model.Controller;

/**
 *
 * @author mama
 */
public class Schedule extends javax.swing.JPanel {
    private DefaultListModel listModel;
    private DodgeballTableModel model1;
    private DodgeballTableModel model2;

    /**
     * Creates new form CurrentStandings
     */
    public Schedule() {
        initComponents();
        fillList();
        fillTable();
    }

    public void setContainer (MainFrame container) {}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuButton = new javax.swing.JButton();
        syncButton = new javax.swing.JButton();
        scheduleLabel = new javax.swing.JLabel();
        matchScroll = new javax.swing.JScrollPane();
        matchList = new javax.swing.JList();
        team1Scroll = new javax.swing.JScrollPane();
        team1Table = new javax.swing.JTable();
        team2Scroll = new javax.swing.JScrollPane();
        team2Table = new javax.swing.JTable();
        matchLabel = new javax.swing.JLabel();
        team1Label = new javax.swing.JLabel();
        team2Label = new javax.swing.JLabel();

        menuButton.setText("Menu");

        syncButton.setText("Sync");
        syncButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                syncButtonActionPerformed(evt);
            }
        });

        scheduleLabel.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        scheduleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scheduleLabel.setText("Schedule");

        matchList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        matchList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                matchListValueChanged(evt);
            }
        });
        matchScroll.setViewportView(matchList);

        team1Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        team1Scroll.setViewportView(team1Table);

        team2Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        team2Scroll.setViewportView(team2Table);

        matchLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        matchLabel.setText("Matches");

        team1Label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        team1Label.setText("Team 1");

        team2Label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        team2Label.setText("Team 2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(menuButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 658, Short.MAX_VALUE)
                        .addComponent(syncButton)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(scheduleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(matchScroll)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(matchLabel)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(team2Scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(team1Scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(team1Label, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(team2Label))
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menuButton)
                    .addComponent(syncButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scheduleLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matchLabel)
                    .addComponent(team1Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(team1Scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(team2Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(team2Scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 2, Short.MAX_VALUE))
                    .addComponent(matchScroll))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void fillList() {
        ArrayList<HashMap<String, Object>> data = new ArrayList();
        try {data = Controller.getData(1);}
        catch (Exception e) {e.printStackTrace();}
        listModel = new DefaultListModel();
        for (HashMap<String, Object> match : data) {
            String s = match.get("team1") + " vs " + match.get("team2") 
                    + " (" + match.get("date") + ")";
            listModel.addElement(s);
        }
        matchList.setModel(listModel);
    }
    
    private void fillTable() {
        String[] columns = {"Player", "Throws", "Hits", "Catches", "Hit Out", "Caught Out", "Survivor"};
        model1 = new DodgeballTableModel(columns);
        model2 = new DodgeballTableModel(columns);
        team1Label.setText("Team 1");
        team2Label.setText("Team 2");
        double match = matchList.getSelectedIndex() + 1;
        if (match != 0) {
            String selected = matchList.getSelectedValue().toString();
            String team1 = selected.substring(0, selected.indexOf(" vs "));
            team1Label.setText(team1);
            String team2 = selected.substring(selected.indexOf(" vs ") + 4, selected.indexOf(" ("));
            team2Label.setText(team2);
            ArrayList<HashMap<String, Object>> dataSet = new ArrayList();
            try {dataSet = Controller.getData(2);}
            catch (Exception e) {e.printStackTrace();}
            for (HashMap<String, Object> data : dataSet) {
                if (data.get("match").equals(match)) {
                    HashMap<String, Object> clone = (HashMap)(data.clone());
                    clone.remove("match");
                    clone.remove("team");
                    if (data.get("team").equals(team1)) model1.addRow(clone.values().toArray());
                    else if (data.get("team").equals(team2)) model2.addRow(clone.values().toArray());
                }
            }
        }
        team1Table.setModel(model1);
        team2Table.setModel(model2);
    }
    
    private void syncButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_syncButtonActionPerformed
        try {Controller.sync();}
        catch (Exception e) {e.printStackTrace();}
        fillList();
        fillTable();
    }//GEN-LAST:event_syncButtonActionPerformed

    private void matchListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_matchListValueChanged
        fillTable();
    }//GEN-LAST:event_matchListValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel matchLabel;
    private javax.swing.JList matchList;
    private javax.swing.JScrollPane matchScroll;
    public javax.swing.JButton menuButton;
    private javax.swing.JLabel scheduleLabel;
    private javax.swing.JButton syncButton;
    private javax.swing.JLabel team1Label;
    private javax.swing.JScrollPane team1Scroll;
    private javax.swing.JTable team1Table;
    private javax.swing.JLabel team2Label;
    private javax.swing.JScrollPane team2Scroll;
    private javax.swing.JTable team2Table;
    // End of variables declaration//GEN-END:variables
}
