/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pages;

import logic.*;
import java.util.ArrayList;

/**
 *
 * @author mama
 */
public class CurrentStandings extends Page {
    private LeaderboardModel model;

    private void fillTable() {
        String[] columns = {"Player", "Team", "Throws", "Hits", "Catches", "H-Out", "C-Out", "S-Bonus", "Hit %",
                "Games", "Points/Games", "Total Points",};
        model = new LeaderboardModel(columns);
        standings.setModel(model);
        ArrayList<Object[]> data = SSTDodgeballStats.getData();
        for (int i = 0; i < data.size(); i++) {
            model.addPlayer(data.get(i));
        }
    }
    
    /**
     * Creates new form CurrentStandings
     */
    public CurrentStandings() {
        initComponents();
        String[] columns = {"Player", "Team", "Throws", "Hits", "Catches", "H-Out", "C-Out", "S-Bonus", 
            "Hit %", "Games", "Points/Games", "Total Points"};
        model = new LeaderboardModel(columns);
        standings.setModel(model);
        fillTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuButton = new javax.swing.JButton();
        syncButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        standings = new javax.swing.JTable();

        menuButton.setText("Menu");
        menuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButtonActionPerformed(evt);
            }
        });

        syncButton.setText("Sync");
        syncButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                syncButtonActionPerformed(evt);
            }
        });

        standings.setAutoCreateRowSorter(true);
        standings.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Player", "Team", "Score"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        standings.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(standings);
        if (standings.getColumnModel().getColumnCount() > 0) {
            standings.getColumnModel().getColumn(0).setResizable(false);
            standings.getColumnModel().getColumn(1).setResizable(false);
            standings.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(menuButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 806, Short.MAX_VALUE)
                        .addComponent(syncButton)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(menuButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(syncButton)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void menuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButtonActionPerformed
        container.switchPage("Main Menu");
    }//GEN-LAST:event_menuButtonActionPerformed

    private void syncButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_syncButtonActionPerformed
        SSTDodgeballStats.sync();
        fillTable();
    }//GEN-LAST:event_syncButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton menuButton;
    private javax.swing.JTable standings;
    private javax.swing.JButton syncButton;
    // End of variables declaration//GEN-END:variables
}
